import React, { useEffect, useState } from "react";
import rightWing from "../../img/rightWing.png";
import leftWing from "../../img/leftWing.png";
import mc from "./header.module.scss";
import { NavLink } from "react-router-dom";

const Header = () => {
  const token = localStorage.getItem("token");
  const [user, setUser] = useState({});

  const getUser = async () => {
    try {
      const response = await fetch("http://localhost:4069/users/getone", {
        headers: {
          Authorization: `${token}`,
        },
      });
      const data = await response.json();
      setUser(data.user);
    } catch (err) {
      return Error(err.message);
    }
  };
  useEffect(() => {
    getUser();
  }, []);
  return (
    <header>
      <div className={`${mc.container}`}>
        <div className={`${mc.bloclogo}`}>
          <img
            src={rightWing}
            alt="logo of a right wing, generated by MidJourney (https://midjourney.com/home/?callbackUrl=%2Fapp%2F)"
          />
          <h1>Future Warfare Corporation</h1>
          <img
            src={leftWing}
            alt="logo of a left wing, generated by MidJourney (https://midjourney.com/home/?callbackUrl=%2Fapp%2F)"
          />
        </div>
        <nav>
          <ul>
            <li>
              <NavLink
                to={"/"}
                className={({ isActive }) => (isActive ? "active" : "inactive")}
              >
                Home
              </NavLink>
            </li>
            <li>
              <NavLink
                to={"/about"}
                className={({ isActive }) => (isActive ? "active" : "inactive")}
              >
                About Us
              </NavLink>
            </li>
            <li>
              <NavLink
                to={"/shop"}
                className={({ isActive }) => (isActive ? "active" : "inactive")}
              >
                Shop
              </NavLink>
            </li>
            <li>
              {!token ? (
                <NavLink
                  to={"/signin"}
                  className={({ isActive }) =>
                    isActive ? "active" : "inactive"
                  }
                >
                  Log-in
                </NavLink>
              ) : (
                <div className={`${mc.custom}`}>
                  <p>Bienvenue {user.username}</p>
                </div>
              )}
            </li>
          </ul>
        </nav>
      </div>
    </header>
  );
};

export default Header;
